# Generated by Django 4.1.4 on 2022-12-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=100, verbose_name='Placa')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('veiculo', models.CharField(max_length=100, verbose_name='Veículo')),
                ('imagem', models.ImageField(null=True, upload_to='imagens/', verbose_name='Imagem')),
            ],
        ),
    ]
