# Generated by Django 4.1.4 on 2022-12-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cnh', models.CharField(max_length=100, verbose_name='CNH')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=100, verbose_name='Placa')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('veiculo', models.CharField(max_length=100, verbose_name='Veículo')),
                ('km', models.IntegerField(verbose_name='Km_Troca_Óleo')),
                ('imagem', models.ImageField(null=True, upload_to='imagens/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_saida', models.DateField(verbose_name='Data_Saida')),
                ('hora_saida', models.TimeField(verbose_name='Hora_Saida')),
                ('km_saida', models.IntegerField(verbose_name='Km_Saida')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('data_retorno', models.DateField(verbose_name='Data_Retorno')),
                ('hora_retorno', models.TimeField(verbose_name='Hora_Retorno')),
                ('km_retorno', models.IntegerField(verbose_name='Km_Retorno')),
                ('km_percorrido', models.IntegerField(verbose_name='Km_Percorrido')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.motorista', verbose_name='ID_Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.veiculo', verbose_name='ID_Veiculo')),
            ],
        ),
    ]
