# Generated by Django 4.1.4 on 2022-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='km',
            field=models.CharField(default=12, max_length=100, verbose_name='Km_Troca_Óleo'),
            preserve_default=False,
        ),
    ]
