# Generated by Django 4.1.4 on 2022-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veiculo', models.CharField(max_length=100, verbose_name='Veiculo')),
                ('motorista', models.CharField(max_length=100, verbose_name='Motorista')),
                ('data_saida', models.DateField(verbose_name='Data_Saida')),
                ('hora_saida', models.TimeField(verbose_name='Hora_Saida')),
                ('km_saida', models.IntegerField(verbose_name='Km_Saida')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('data_retorno', models.DateField(verbose_name='Data_Retorno')),
                ('hora_retorno', models.TimeField(verbose_name='Hora_Retorno')),
            ],
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='km',
            field=models.IntegerField(verbose_name='Km_Troca_Óleo'),
        ),
    ]
