# Generated by Django 4.1.4 on 2022-12-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_controle_alter_motorista_telefone_alter_veiculo_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.motorista', verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.veiculo', verbose_name='Veiculo'),
        ),
    ]
