# Generated by Django 4.1.4 on 2022-12-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_controle_motorista_alter_controle_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='km_percorrido',
            field=models.IntegerField(default=15, verbose_name='Hora_Pergorrido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controle',
            name='km_retorno',
            field=models.IntegerField(default=15, verbose_name='Km_Retorno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controle',
            name='hora_retorno',
            field=models.IntegerField(verbose_name='Hora_Retorno'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.motorista', verbose_name='ID_Motorista'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.veiculo', verbose_name='ID_Veiculo'),
        ),
    ]
