# Generated by Django 4.1.4 on 2022-12-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_controle_km_percorrido_controle_km_retorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='hora_retorno',
            field=models.TimeField(verbose_name='Hora_Retorno'),
        ),
    ]
