# Generated by Django 4.1.4 on 2022-12-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_alter_controle_hora_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='km_percorrido',
            field=models.IntegerField(verbose_name='Km_Pergorrido'),
        ),
    ]
